# SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

openapi: 3.0.3
info:
  title: Carbonio Docs Connector API
  description: Carbonio Docs Connector API
  version: latest
servers:
  - url: 'https://example.com/services/docs/'
tags:
  - name: files
  - name: wopi
    description: Allows carbonio-docs-editor to manipulate the attributes and the blob of a file. They are exposed only internally.
paths:
  /files/create:
    post:
      description: Create a new empty Docs file
      operationId: createFile
      parameters:
        - $ref: '#/components/parameters/headerCookies'
      requestBody:
        $ref: '#/components/requestBodies/InsertFileRequest'
      responses:
        '200':
          $ref: '#/components/responses/200CreatedFileResponse'
      tags:
        - files
  /files/open/{nodeId}:
    get:
      description: Open an existing file with Docs. When the version is not specified, it will open the last one
      operationId: openFile
      parameters:
        - $ref: '#/components/parameters/headerCookies'
        - $ref: '#/components/parameters/pathNodeId'
        - $ref: '#/components/parameters/queryNodeVersion'
        - $ref: '#/components/parameters/queryRedirect'
      responses:
        '307':
          $ref: '#/components/responses/307DocsEditorRedirectResponse'
      tags:
        - files
  /wopi/{nodeId}:
    get:
      description: Retrieve docs-editor attributes
      operationId: docsEditorAttributes
      parameters:
        - $ref: '#/components/parameters/queryAccessToken'
        - $ref: '#/components/parameters/pathNodeId'
        - $ref: '#/components/parameters/queryNodeVersion'
      responses:
        '200':
          $ref: '#/components/responses/200DocsEditorAttributesResponse'
      tags:
        - wopi
  /wopi/{nodeId}/contents:
    get:
      description: Retrieve blob of a specific Files node
      operationId: getBlob
      parameters:
        - $ref: '#/components/parameters/queryAccessToken'
        - $ref: '#/components/parameters/pathNodeId'
        - $ref: '#/components/parameters/queryNodeVersion'
      responses:
        '200':
          $ref: '#/components/responses/200DownloadNodeResponse'
      tags:
        - wopi
    post:
      description: Save the updated blob of a specific Files node
      operationId: saveBlob
      parameters:
        - $ref: '#/components/parameters/headerCoolIsAutosave'
        - $ref: '#/components/parameters/headerCoolIsExitSave'
        - $ref: '#/components/parameters/headerContentLength'
        - $ref: '#/components/parameters/pathNodeId'
        - $ref: '#/components/parameters/queryAccessToken'
      requestBody:
        $ref: '#/components/requestBodies/SaveBlobRequest'
      responses:
        '200':
          $ref: '#/components/responses/200NodeUpdatedTimestampResponse'
      tags:
        - wopi
components:
  parameters:
    headerCookies:
      in: header
      name: Cookie
      required: true
      schema:
        type: string

    headerContentLength:
      in: header
      name: Content-Length
      schema:
        type: integer
        format: int64

    headerCoolIsAutosave:
      in: header
      name: X-COOL-WOPI-IsAutosave
      schema:
        type: boolean

    headerCoolIsExitSave:
      in: header
      name: X-COOL-WOPI-IsExitSave
      schema:
        type: boolean

    pathNodeId:
      in: path
      name: nodeId
      required: true
      schema:
        type: string
        format: uuid
      description: The id of the Files node

    queryNodeVersion:
      in: query
      name: version
      schema:
        type: integer
      required: false
      description: The version of the Files node

    queryRedirect:
      in: query
      name: redirect
      schema:
        type: boolean
      required: false
      description: Allows to specify if the response of the API should return a 307 or a 200 status code with the URL in the json response

    queryAccessToken:
      in: query
      name: access_token
      schema:
        type: string
      required: true
      description: Token necessary to validate wopi requests. It is mapped to the opened file.

  requestBodies:
    InsertFileRequest:
      description: New Docs file metadata
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InsertFile'

    SaveBlobRequest:
      description: Save the blob
      content:
        application/octet-stream:
          schema:
            $ref: '#/components/schemas/NodeBinary'

  responses:
    200CreatedFileResponse:
      description: The metadata of the new created Docs file
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreatedFile'

    307DocsEditorRedirectResponse:
      description: URL necessary to redirect to an url that talks with carbonio-docs-editor
      headers:
        location:
          schema:
            type: string

    200DownloadNodeResponse:
      description: Return the requested blob
      content:
        application/octet-stream:
          schema:
            $ref: '#/components/schemas/NodeBinary'

    200DocsEditorAttributesResponse:
      description: All the attributes necessary to carbonio-docs-editor in order to open a file correctly
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DocsEditorAttributes'

    200NodeUpdatedTimestampResponse:
      description: Updated timestamp of the saved blob
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NodeUpdatedTimestamp'
  schemas:
    InsertFile:
      type: object
      required:
        - filename
        - destinationFolderId
        - type
      properties:
        filename:
          type: string
          description: "Filename of the file to be created (without the extension)"
          example: New spreadsheet
        destinationFolderId:
          type: string
          description: "Folder id where the file is created. The Root id is LOCAL_ROOT"
          example: c533b987-2cfa-4033-8717-665e680df6f3
        type:
          type: string
          enum: [
            LIBRE_DOCUMENT,
            LIBRE_SPREADSHEET,
            LIBRE_PRESENTATION,
            MS_DOCUMENT,
            MS_SPREADSHEET,
            MS_PRESENTATION
          ]
          description: "Docs file type. It can be:\n
           - LIBRE_DOCUMENT, LIBRE_SPREADSHEET or LIBRE_PRESENTATION to upload open document format\n
           - MS_DOCUMENT, MS_SPREADSHEET or MS_PRESENTATION to upload Microsoft Office document format"
          example: LIBRE_DOCUMENT

    CreatedFile:
      type: object
      properties:
        nodeId:
          type: string
          format: uuid
          description: "Id of the created Docs file"
          example: 5564df1e-a16a-4d74-9c74-15e77ac9d473

    DocsEditorAttributes:
      type: object
      properties:
        OwnerId:
          type: string
          format: uuid
        UserId:
          type: string
          format: uuid
        UserFriendlyName:
          type: string
        UserCanWrite:
          type: boolean
        BaseFileName:
          type: string
        Version:
          type: integer
        Size:
          type: integer
          format: int64
        LastModifiedTime:
          type: string
        EnableOwnerTermination:
          type: boolean
        DisableCopy:
          type: boolean
        DisableExport:
          type: boolean
        DisablePrint:
          type: boolean
        DisableInactiveMessages:
          type: boolean
        HideExportOption:
          type: boolean
        HideSaveOption:
          type: boolean
        HidePrintOption:
          type: boolean
        HideChangeTrackingControls:
          type: boolean
        UserCanNotWriteRelative:
          type: boolean
        UserCanRename:
          type: boolean
        SupportsLocks:
          type: boolean

    NodeUpdatedTimestamp:
      type: object
      properties:
        LastModifiedTime:
          type: string

    NodeBinary:
      type: string
      format: binary
