#!/bin/bash

# SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

JAVA_HOME="/usr/share/carbonio/docs-connector:/opt/zextras/common/lib/jvm/java"
export JAVA_HOME
/opt/zextras/common/bin/java \
  -Djava.net.preferIPv4Stack=true \
  -Xmx128m \
  -DLOG_LEVEL=warn \
  -jar /usr/share/carbonio/carbonio-docs-connector.jar
